### ISSUE TITLE
Video upload is very slow

### ISSUE THREAD

**Issue by miahuynhh** [miahuynhh/footnote#58]
* Behavior: video is taking a long time to be successfully uploaded to DigitalOcean Spaces
* Steps to Reproduce:
  * Start the front and back end
  * Create an account / Log in
  * Create a new project
  * Open the browser inspector tool and go to Console tab
  * Open terminal in IDE (keep an eye out for "POST /videos/upload-video 200" message in terminal)
  * Upload a video from local machine of length 15 seconds or above
  * Look in terminal for how long it takes for the request to be successful (for example `POST /videos/upload-video 200 372629.520 ms`)
    * (videos that are even just 15 seconds long take a while to upload)
* Device: MacBook Air; OS: MacOS; Browser: Chrome
* This issue is more of a scalability issue - can look into expanding our DigitalOcean bandwidth or improving backend implementation for video upload. Not crucial for beta but crucial for final release.

**Comment by Purplecannon** [comment]
Tried to reproduce using the steps described above. The video for testing was 3.8MB, but was successfully uploaded in a few second, which I wouldn't define as too slow. 

The above mentioned problem could due to an occasional network issue. 

As for the current video uploading scheme and backend software, there isn't much to change or improve without changing the design.

Because of the reasons mentioned above, this will not (need not) to be fixed.
