### ISSUE TITLE
Multiple projects with the same exact title

### ISSUE THREAD

**Issue by alsiu7** [miahuynhh/footnote#71]
Summary: (Bug? / Enhancement?)
Multiple projects can have the same title.

Component:
Frontend pages (Home page)
Backend (Maybe?)

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
After creating a new project and then giving it a some title, a user can go back and create a new project with the same exact title. This could be a little confusing to users especially when there is not way to differentiate the projects.

**Comment by miahuynhh** [comment]
Thank you for pointing that out! :) We had planned to allow the user to create projects with the same title - which is why we have the different project ids stored internally in the program. 
We are working on a thumbnail functionality that could help differentiate the projects.
Do you recommend not allowing users to create with the same title?

**Comment by alsiu7** [comment]
I like the idea of a thumbnail, and if you're considering this then having projects with the same title may not be a major issue.
